[master]
${master-1_address}
${master-2_address}
${master-3_address}


[all:vars]
dns = ${internal_lb_dns}
ansible_ssh_extra_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3