- hosts: all
  become: yes
  tasks:
    - name: Remove packages
      apt:
        pkg:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - runc
        state: absent

    - name: Install packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present
        update_cache: yes

    - debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']

    - name: Add docker GPG apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Add apt key for kubernetes
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Repository for kubernetes
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes.list

    - name: Install Packages
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - kubeadm
          - kubelet
          - kubectl

    - name: Create directory for storing daemon.json
      copy:
        src: daemon.json
        dest: /etc/docker/daemon.json

    - name: Create directory for docker daemon
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /etc/systemd/system/docker.service.d
        - /etc/default

    - name: Create directory for docker daemon
      file:
        path: /etc/default/kubelet
        state: touch

    - name: Configure node ip
      lineinfile:
        path: /etc/default/kubelet
        line: KUBELET_EXTRA_ARGS=--node-ip={{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}

    - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
      sysctl:
        name: net.bridge.bridge-nf-call-ip6tables
        value: 1
        state: present

    - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: 1
        state: present

    - name: Enable Kernel Module overlay
      modprobe:
        name: "{{item}}"
        state: present
      with_items:
        - overlay
        - br_netfilter

    - name: Reload Daemon
      shell: systemctl daemon-reload

    - name: Enable sysctl
      command: sysctl --system

    - name: Restart docker service
      service:
        name: docker
        state: restarted
        enabled: yes

    - name: Restart Kubelet
      service:
        name: kubelet
        state: restarted
        enabled: yes
